on:
  push:
    branches:
      - main

name: Release Packaging

jobs:
  release:
    name: Release Packaging
    env:
      PROJECT_NAME_UNDERSCORE: rp_pico_midi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: thumbv6m-none-eabi
          override: true
      - name: Install libudev
        run: sudo apt-get install libudev-dev
      - name: Install elf2uf2-rs
        run: cargo install elf2uf2-rs
      - name: Release Build
        run: cargo build --release
      - name: Convert ELF to UF2
        run: elf2uf2-rs target/release/${{ env.PROJECT_NAME_UNDERSCORE }} ${{ env.PROJECT_NAME_UNDERSCORE }}.uf2
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT_NAME_UNDERSCORE }}.uf2
          path: ${{ env.PROJECT_NAME_UNDERSCORE }}.uf2
